jenkins:
  systemMessage: "Jenkins configured using JCasC"
  numExecutors: 1
  mode: NORMAL
  disableRememberMe: false

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
        
        - id: "iamakshu"
          password: "${JENKINS_USER1_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "${JENKINS_URL}"

  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://localhost:9000"
        credentialsId: "sonarqube-token"
  
tool:
  jdk:
    installations:
      - name: "JDK-21"
        home: "/usr/lib/jvm/temurin-21-jdk-amd64"

  maven:
    installations:
      - name: "maven"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.11"

credentials:
  system:
    domainCredentials:
      - credentials: 
          - string:
              scope: GLOBAL
              id: "sonarqube-token"
              secret: "${SONARQUBE_TOKEN}"
              description: "SonarQube Project Analysis Token"

          - string:
              scope: GLOBAL
              id: "nvd-api-key"
              secret: "${NVD_API_KEY}"
              description: "NVD API Key"
              
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub-creds"
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_TOKEN}"
              description: "Docker Hub credentials"

          - file:
              scope: GLOBAL
              id: "cosign-private-key"
              fileName: "cosign.key"
              secretBytes: "${COSIGN_PRIVATE_KEY}"
              description: "Cosign image signing private key"

          - string:
              scope: GLOBAL
              id: "cosign-key-password"
              secret: "${COSIGN_KEY_PASSWORD}"
              description: "Cosign private key password"

# nexus-credentials    -> needed only for Nexus push
# github-credentials   -> needed only for private Git or GitOps push

# slack-webhook        -> needed only when Slack notifications are enabled
# teams-webhook        -> needed only when Teams notifications are enabled