apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-tls
  namespace: petclinic-dev
spec:
  secretName: petclinic-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - petclinic.local