apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-secret-reader
  namespace: petclinic-dev
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cosign-public-key"]
    verbs: ["get"]

# kubectl create role kyverno-secret-reader --verb=get --resource=secrets --resource-name=cosign-public-key -n petclinic-dev --dry-run=client -o yaml > kyverno-role.yml
