apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy-one
  namespace: petclinic-dev
spec:
  podSelector:
    matchLabels:
      app: postgres

  policyTypes:
  - Ingress # allowed incoming traffic from app to db

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: petclinic-app
    ports:
    - protocol: TCP
      port: 5432

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy-two
  namespace: petclinic-dev
spec:
  podSelector:
    matchLabels:
      app: petclinic-app

  policyTypes:
  - Ingress # allowed incoming traffic from ingress to app
  - Egress # allowed outgoing traffic to db from app

  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080

  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53