# Default values for petclinic-app.
# This is a YAML-formatted file.


appName: petclinic
dbName: postgres

app:
  replicas: 2
  maxUnavailable: 2
  maxSurge: 1
  containerImage: docker.io/maramaroua/spring-petclinic
  imageTag: 8
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc:5432/petclinic
    SPRING_DATASOURCE_USERNAME: petclinic

  livenessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  servicePort: 8080

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  ingress:
    port: 8080
    path: /


db:
  replicas: 1
  minReadySeconds: 10
  containerImage: docker.io/postgres:15
  env:
    POSTGRES_USER: petclinic
    POSTGRES_DB: petclinic
  volumeName: db-data
  mountPath: /var/lib/postgresql/data
  pvcStorage: 1Gi

  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  servicePort: 5432


CAIssuer: selfsigned-issuer

secret:
  postgres:
    name: postgres-secret
    key: POSTGRES_PASSWORD
    password: petclinic

limitRange:
  default:
    cpu: 500m
    memory: 512Mi
  defaultRequest:
    cpu: 250m
    memory: 256Mi
  max:
    cpu: "1"
    memory: 1Gi
  min:
    cpu: 100m
    memory: 128Mi

resourceQuota:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "9"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"