apiVersion: v1
data:
  cosign.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRURONDVZT1BpY0ZmUGJENTM3Q1oyM1R0YVQyeDgNCitjTHFRVlZLT1BMWmRDYW5ZQS9YaVJUNzJqdUxkUFZoQkc1ajBiYXlkNyt3VkZGS1pmV1V0SEFabEE9PQ0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
kind: Secret
metadata:
  name: cosign-public-key
  namespace: {{ .Release.Namespace }}
