apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-resource-limits
  namespace: {{ .Release.Namespace }}
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-resource-limits
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: "CPU and memory limits are required on all containers."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"

---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-ns-labels
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - name: add-managed-by-label
      match:
        any:
          - resources:
              kinds: [Pod]
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              managed-by: dev-team

---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restrict-image-registries
  namespace: {{ .Release.Namespace }}
spec:
  validationFailureAction: Enforce
  rules:
    - name: validate-registries
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: "Images must come from docker.io, gcr.io, or quay.io only."
        pattern:
          spec:
            containers:
              - image: "docker.io/* | gcr.io/* | quay.io/* | nginx:* | busybox:* | alpine:* | hashicorp/*"

---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: verify-cosign-signature
  namespace: {{ .Release.Namespace }}
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-image-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "{{ .Values.app.containerImage }}*"
          repository: index.docker.io/iamakshu/petclinic-app
          required: true
          verifyDigest: true
          mutateDigest: true
          useCache: false
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDN45YOPicFfPbD537CZ23TtaT2x8
                      +cLqQVVKOPLZdCanYA/XiRT72juLdPVhBG5j0bayd7+wVFFKZfWUtHAZlA==
                      -----END PUBLIC KEY-----
