apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-secret-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cosign-public-key"]
    verbs: ["get"]
