apiVersion: v1
kind: LimitRange
metadata:
  name: dev-containers-limit-range
  namespace: petclinic-dev
spec:
  limits:
    - default:
        cpu: {{ .Values.limitRange.default.cpu }}
        memory: {{ .Values.limitRange.default.memory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu }}
        memory: {{ .Values.limitRange.defaultRequest.memory }}
      max:
        cpu: {{ .Values.limitRange.max.cpu }}
        memory: {{ .Values.limitRange.max.memory }}
      min:
        cpu: {{ .Values.limitRange.min.cpu }}
        memory: {{ .Values.limitRange.min.memory }}
      type: Container