apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ index .Values.resourceQuota.hard "requests.cpu" | quote }}
    requests.memory: {{ index .Values.resourceQuota.hard "requests.memory" | quote }}
    limits.cpu: {{ index .Values.resourceQuota.hard "limits.cpu" | quote }}
    limits.memory: {{ index .Values.resourceQuota.hard "limits.memory" | quote }}
    configmaps: {{ .Values.resourceQuota.hard.configmaps | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.hard.persistentvolumeclaims | quote }}
    pods: {{ .Values.resourceQuota.hard.pods | quote }}
    replicationcontrollers: {{ .Values.resourceQuota.hard.replicationcontrollers | quote }}
    secrets: {{ .Values.resourceQuota.hard.secrets | quote }}
    services: {{ .Values.resourceQuota.hard.services | quote }}
    services.loadbalancers: {{ index .Values.resourceQuota.hard "services.loadbalancers" | quote }}
