apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-sa
  namespace: {{ .Release.Namespace }}

#  kubectl create sa petclinic-sa -n petclinic-dev --dry-run=client -o yaml > serviceAccount.yml
